let exp= require('express')
let srv = exp()
let todoroute = require('./route/todo')
srv.use(exp.json())
srv.use(exp.urlencoded({extended : true}))
srv.set('view engine','hbs')
srv.set('views',__dirname + '/view')
srv.use('/todos',todoroute)
srv.listen(8000)
