let exp= require('express')
let srv = exp()
let todoroute = require('./routes/adder')
srv.use(exp.json())
srv.use(exp.urlencoded({extended : true}))
srv.set('view engine','hbs')
srv.set('views',__dirname + '/views')
srv.use('/todo',todoroute)
srv.listen(8000) 
