let exp = require('express')
let helper = require('./route/helper')
let srv = exp()
srv.use(exp.json())
srv.use(exp.urlencoded({extended:true}))
srv.set('view engine','hbs')
srv.set('views',__dirname+'/view')
srv.use('/help',helper)
srv.listen(8080)